name: Bannu
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera:
  email_validator:
  dio:
  json_annotation: ^4.8.1
  provider: ^6.1.1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  uses-material-design: true
  assets:
     - assets/images/bannu.jpg
     - assets/images/icon_android.png

flutter_icons:
  android: true
  ios: true
  image_path: "icons/ic_launcher.png"
  adaptive_icon_background: "#FFFFFF"

#  flutter pub run flutter_launcher_icons:main

flutter_native_splash:
  image: "assets/images/icon_android.png"
  color: "#42a5f5"
